let handler = async (m, { conn, usedPrefix, text }) => {
 
m.reply(`_Tunggu, Dukun sedang cek khodam kamu`)
await sleep(1500) 
m.reply("mendapatkan informasi khodam..") 
await sleep(1500) 
m.reply(`khodam kamu adalah : ${await pickRandom(khodam)}`) 
  
};
handler.help = ["cekkhodam"];
handler.tags = ["fun"];
handler.command = /^(cekkhodam)/i;
handler.register = true;
handler.group = true;
export default handler;

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

const khodam = [
  "Singa\n\n*Penjelasan:*",
  "kosoong atau tidak ada\n\n*Penjelasan:*",
  "Harimau\n\n*Penjelasan:*",
  "Elang\n\n*Penjelasan:*",
  "Serigala\n\n*Penjelasan:*",
  "Naga\n\n*Penjelasan:*",
  "Gajah\n\n*Penjelasan:*",
  "Kuda\n\n*Penjelasan:*",
  "Macan Tutul\n\n*Penjelasan:*",
  "Kerbau\n\n*Penjelasan:*",
  "Burung Hantu\n\n*Penjelasan:*",
  "Burung Rajawali\n\n*Penjelasan:*",
  "Ikan Hiu\n\n*Penjelasan:*",
  "Lumba-Lumba\n\n*Penjelasan:*",
  "Ular\n\n*Penjelasan:*",
  "Kura-Kura\n\n*Penjelasan:*",
  "Tupai\n\n*Penjelasan:*",
  "Paus\n\n*Penjelasan:*",
  "Kelelawar\n\n*Penjelasan:*",
  "Kijang\n\n*Penjelasan:*",
  "Banteng\n\n*Penjelasan:*",
  "Rusa\n\n*Penjelasan:*",
  "Anjing\n\n*Penjelasan:*",
  "Kucing\n\n*Penjelasan:*",
  "Buaya\n\n*Penjelasan:*",
  "Kambing\n\n*Penjelasan:*",
  "Kuda Nil\n\n*Penjelasan:*",
  "Bebek\n\n*Penjelasan:*",
  "Angsa\n\n*Penjelasan:*",
  "Ayam\n\n*Penjelasan:*",
  "Merpati\n\n*Penjelasan:*",
  "Burung Beo\n\n*Penjelasan:*",
  "Burung Kenari\n\n*Penjelasan:*",
  "Burung Kakatua\n\n*Penjelasan:*",
  "Bunglon\n\n*Penjelasan:*",
  "Cicak\n\n*Penjelasan:*",
  "Kodok\n\n*Penjelasan:*",
  "Katak\n\n*Penjelasan:*",
  "Tikus\n\n*Penjelasan:*",
  "Landak\n\n*Penjelasan:*",
  "Kanguru\n\n*Penjelasan:*",
  "Koala\n\n*Penjelasan:*",
  "Panda\n\n*Penjelasan:*",
  "Beruang\n\n*Penjelasan:*",
  "Rubah\n\n*Penjelasan:*",
  "Lynx\n\n*Penjelasan:*",
  "Leopard\n\n*Penjelasan:*",
  "Jaguar\n*Penjelasan:*",
  "Cheetah\n\n*Penjelasan:*",
  "Badak\n\n*Penjelasan:*",
  "Zebra\n\n*Penjelasan:*",
  "Antelop\n\n*Penjelasan:*",
  "Unta\n\n*Penjelasan:*",
  "Alpaka\n\n*Penjelasan:*",
  "Llama\n\n*Penjelasan:*",
  "Serigala Abu-abu\n\n*Penjelasan:*",
  "Serigala Merah\n\n*Penjelasan:*",
  "Serigala Putih\n\n*Penjelasan:*",
  "Lynx\n\n*Penjelasan:*",
  "Harimau Putih\n\n*Penjelasan:*",
  "Harimau Siberia\n\n*Penjelasan:*",
  "Harimau Sumatra\n\n*Penjelasan:*",
  "Gorila\n\n*Penjelasan:*",
  "Orangutan\n\n*Penjelasan:*",
  "Simpanse\n\n*Penjelasan:*",
  "Monyet\n\n*Penjelasan:*",
  "Babun\n\n*Penjelasan:*",
  "Lemur\n\n*Penjelasan:*",
  "Iguana\n\n*Penjelasan:*",
  "Komodo\n\n*Penjelasan:*",
  "Salamander\n\n*Penjelasan:*",
  "Belut\n\n*Penjelasan:*",
  "Sotong\n\n*Penjelasan:*",
  "Gurita\n\n*Penjelasan:*",
  "Kepiting\n\n*Penjelasan:*",
  "Lobster\n\n*Penjelasan:*",
  "Udang\n\n*Penjelasan:*",
  "Kupu-kupu\n\n*Penjelasan:*",
  "Lebah\n\n*Penjelasan:*",
  "Tawon\n\n*Penjelasan:*",
  "Kumbang\n\n*Penjelasan:*",
  "Belalang\n\n*Penjelasan:*",
  "Jangkrik\n\n*Penjelasan:*",
  "Semut\n\n*Penjelasan:*",
  "Kecoak\n\n*Penjelasan:*",
  "Laba-laba\n\n*Penjelasan:*",
  "Kalajengking\n\n*Penjelasan:*",
  "Serangga Tongkat\n\n*Penjelasan:*",
  "Naga Laut\n\n*Penjelasan:*",
  "Kuda Laut\n\n*Penjelasan:*",
  "Duyung\n\n*Penjelasan:*",
  "Putri Duyung\n\n*Penjelasan:*",
  "Burung Kolibri\n\n*Penjelasan:*",
  "Burung Hantu Salju\n\n*Penjelasan:*",
  "Burung Puyuh\n\n*Penjelasan:*",
  "Burung Gagak\n\n*Penjelasan:*",
  "Burung Pelikan\n\n*Penjelasan:*",
  "Burung Albatros\n\n*Penjelasan:*",
  "Burung Flamingo\n\n*Penjelasan:*",
  "Burung Hering\n*Penjelasan:*",
  "Burung Camar\n\n*Penjelasan:*",
  "Burung Pinguin\n\n*Penjelasan:*",
    "Cincin\n\n*Penjelasan:*",
    "Batu Akik\n\n*Penjelasan:*",
    "Keris\n\n*Penjelasan:*",
    "Tongkat\n\n*Penjelasan:*",
    "Pusaka\n\n*Penjelasan:*",
    "Patung\n\n*Penjelasan:*",
    "Mustika\n\n*Penjelasan:*",
    "Tasbih\n\n*Penjelasan:*",
    "Kalung\n\n*Penjelasan:*",
    "Gelang\n\n*Penjelasan:*",
    "Permata\n\n*Penjelasan:*",
    "Pedang\n\n*Penjelasan:*",
    "Mata Uang\n\n*Penjelasan:*",
    "Wesi Kuning\n\n*Penjelasan:*",
    "Serat Tali\n\n*Penjelasan:*",
    "Belati\n\n*Penjelasan:*",
    "Cundrik\n\n*Penjelasan:*",
    "Selendang\n\n*Penjelasan:*",
    "Jarum\n\n*Penjelasan:*",
    "Tombak\n\n*Penjelasan:*",
    "Kerikil\n\n*Penjelasan:*",
    "Kendi\n\n*Penjelasan:*",
    "Kain Kafan\n\n*Penjelasan:*",
    "Topi\n\n*Penjelasan:*",
    "Payung\n\n*Penjelasan:*",
    "Sandal\n\n*Penjelasan:*",
    "Kacamata\n\n*Penjelasan:*",
    "Sabuk\n\n*Penjelasan:*",
    "Sarung\n\n*Penjelasan:*",
    "Tali Ikat Pinggang\n\n*Penjelasan:*",
    "Surat\n\n*Penjelasan:*",
    "Kunci\n\n*Penjelasan:*",
    "Lilin\n\n*Penjelasan:*",
    "Peniti\n\n*Penjelasan:*",
    "Sisir\n\n*Penjelasan:*",
    "Cermin\n\n*Penjelasan:*",
    "Kendi Air\n\n*Penjelasan:*",
    "Piring\n\n*Penjelasan:*",
    "Gelas\n\n*Penjelasan:*",
    "Mangkuk\n\n*Penjelasan:*",
    "Sendok\n\n*Penjelasan:*",
    "Sapu\n\n*Penjelasan:*",
    "Gayung\n\n*Penjelasan:*",
    "Tikar\n\n*Penjelasan:*",
    "Bantal\n\n*Penjelasan:*",
    "Guci\n\n*Penjelasan:*",
    "Lentera\n\n*Penjelasan:*",
    "Lampu\n\n*Penjelasan:*",
    "Buku\n\n*Penjelasan:*",
    "Pena\n\n*Penjelasan:*",
    "Dupa\n\n*Penjelasan:*",
    "Asbak\n\n*Penjelasan:*",
    "Cangkir\n\n*Penjelasan:*",
    "Gantungan Kunci\n\n*Penjelasan:*",
    "Kalender\n\n*Penjelasan:*",
    "Sepeda\n\n*Penjelasan:*",
    "Lukisan\n\n*Penjelasan:*",
    "Batu Kerikil\n\n*Penjelasan:*",
    "Batu Kali\n\n*Penjelasan:*",
    "Kipas\n\n*Penjelasan:*",
    "Peci\n\n*Penjelasan:*",
    "Sorban\n\n*Penjelasan:*",
    "Rokok\n\n*Penjelasan:*",
    "Topeng\n\n*Penjelasan:*",
    "Gamelan\n\n*Penjelasan:*",
    "Angklung\n\n*Penjelasan:*",
    "Suling\n\n*Penjelasan:*",
    "Wayang\n\n*Penjelasan:*", 
    "Sepatu\n\n*Penjelasan:*",
    "Jam Tangan\n\n*Penjelasan:*",
    "Kosong atau tidak adaa\n\n*Penjelasan:*",
    "landak sawah\n\n*Penjelasan:*",
"naga hytam\n\n*Penjelasan:*",
"Kuru kuru\n\n*Penjelasan:*",
"kak gem jir\n\n*Penjelasan:*", 
"cicak berenang\n\n*Penjelasan:*",
"tuyul mulet\n\n*Penjelasan:*", 
"serigala botak\n\n*Penjelasan:*", 
"kodok tebu\n\n*Penjelasan:*", 
"ayam kaki 6\n\n*Penjelasan:*", 
"kuntibapa\n\n*Penjelasan:*", 
"harimau ompong\n\n*Penjelasan:*", 
"kuda kudaan\n\n*Penjelasan:*", 
"gajah Mada\n\n*Penjelasan:*", 
"silit wangi\n\n*Penjelasan:*", 
]